version: '3'
services:
  backend:
    build: Back-End
    container_name: backend
    ports:
      - "2023:2023"
    env_file:
      - backenvfile
  frontend:
    build: Front-End
    container_name: frontend
    environment:
      VITE_API_DOMAIN: "backend:2023/api/v1/"
    ports:
      - "5173:5173"
    depends_on:
      - backend
